var cube3D = document.querySelector("._3dbox"), scene = document.querySelector(".wraper"), sideLeft = document.querySelector("._3dface__left"), sideRight = document.querySelector("._3dface__right"), sideRotate = 0, allBtn = Array.from(document.querySelectorAll(".buttom"));
window.requestAnimationFrame(function () { window.requestAnimationFrame(function () { allBtn[0].addEventListener("click", function () { return animoFlip(1, 0, 0, sideRotate -= 90) }); allBtn[1].addEventListener("click", function () { return animoFlip(1, 0, 0, sideRotate += 90) }); allBtn[2].addEventListener("click", function () { return animoFlip(0, 1, 0, sideRotate += 90) }); allBtn[3].addEventListener("click", function () { return animoFlip(0, 1, 0, sideRotate -= 90) }) }) });
function clearSideHor(b) { sideRight.classList.remove("js-animo_SizeHor"); sideLeft.classList.remove("js-animo_SizeHor") } function zoomSideHor(b) { clearSideHor(b); -90 == b ? sideRight.classList.add("js-animo_SizeHor") : 90 == b && sideLeft.classList.add("js-animo_SizeHor") }
function animoFlip(b, c, d, a) {
   cube3D.style.setProperty("--flipZoom", .5); scene.classList.add("js-add-perspectiv"); cube3D.style.setProperty("--flipX", +b); cube3D.style.setProperty("--flipY", +c); cube3D.style.setProperty("--flipZ", +d); cube3D.style.setProperty("--flipDeg", +a + "deg"); cube3D.addEventListener("transitionend", function () { window.requestAnimationFrame(function () { window.requestAnimationFrame(function () { cube3D.style.setProperty("--flipZoom", 1); scene.classList.remove("js-add-perspectiv"); zoomSideHor(a) }) }) });
   sideRotate = a; changeMapNavSegmVert(b, c, d, a); bottomHidden(b, c, d, a); clearSideHor(a); animoStartGuns(b, c, d, a); animoStartCyber(b, c, d, a); animoStartCars(b, c, d, a)
}
function bottomHidden(b, c, d, a) {
   0 == a && 0 == b && 1 == c ? (allBtn[0].style.visibility = "visible", allBtn[1].style.visibility = "visible", allBtn[2].style.visibility = "visible", allBtn[3].style.visibility = "visible") : 0 == a && 1 == b && 0 == c ? (allBtn[0].style.visibility = "visible", allBtn[1].style.visibility = "visible", allBtn[2].style.visibility = "visible", allBtn[3].style.visibility = "visible") : 90 == a && 1 == b && 0 == c ? (allBtn[0].style.visibility = "visible", allBtn[1].style.visibility = "hidden", allBtn[2].style.visibility = "hidden", allBtn[3].style.visibility =
      "hidden") : -90 == a && 1 == b && 0 == c ? (allBtn[0].style.visibility = "visible", allBtn[1].style.visibility = "visible", allBtn[2].style.visibility = "hidden", allBtn[3].style.visibility = "hidden") : -180 == a && 1 == b && 0 == c ? (allBtn[0].style.visibility = "hidden", allBtn[1].style.visibility = "visible", allBtn[2].style.visibility = "hidden", allBtn[3].style.visibility = "hidden") : 90 == a && 0 == b && 1 == c ? (allBtn[0].style.visibility = "hidden", allBtn[1].style.visibility = "hidden", allBtn[2].style.visibility = "hidden", allBtn[3].style.visibility = "visible") :
         -90 == a && 0 == b && 1 == c && (allBtn[0].style.visibility = "hidden", allBtn[1].style.visibility = "hidden", allBtn[2].style.visibility = "visible", allBtn[3].style.visibility = "hidden")
}
function animoStartGuns(b, c, d, a) {
   d = document.querySelector(".all__info-guns"); var e = document.querySelector(".content__items-guns"), f = Array.from(document.querySelectorAll(".info__guns")); 90 == a && 1 == b && 0 == c ? (d.classList.add("js-add-all__info-guns"), e.classList.add("js-add-items-guns")) : 90 !== a ? (d.classList.remove("js-add-all__info-guns"), e.classList.remove("js-add-items-guns"), f.forEach(function (g) { g.classList.remove("js-add-triger__info-guns") })) : 1 == c && (d.classList.remove("js-add-all__info-guns"), e.classList.remove("js-add-items-guns"),
      f.forEach(function (g) { g.classList.remove("js-add-triger__info-guns") }))
} function animoStartCyber(b, c, d, a) { var e = document.querySelector(".body__cyberware"); c = Array.from(document.querySelectorAll(".cyber__info ")); -180 == a && 1 == b ? setTimeout(function () { e.classList.add("js-add-cyberware") }, 1500) : -180 !== a && (e.classList.remove("js-add-cyberware"), c.forEach(function (f) { f.classList.remove("js-add-triger__implants") })) }
function animoStartCars(b, c, d, a) { var e = document.querySelector(".title-cars"); 90 == a && 1 == c ? cube3D.addEventListener("transitionend", function () { window.requestAnimationFrame(function () { window.requestAnimationFrame(function () { e.classList.add("js-add-cars__title") }) }) }) : 90 !== a && e.classList.remove("js-add-cars__title") };